- hosts: sonar
  pre_tasks:
    - name: Update all the packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: Install Dependencies
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - unzip #Used for Sonarqube installation
        - curl #Used to get the files
        - epel-release #used for HTTPD installation
        - postgresql-libs #used by psycopg2
        - python-psycopg2 #Used for PostgreSQL authentication
        - policycoreutils-python #Used to edit Selinux
      become: true

  roles:
    - {role: sonarqube }
